coyote_api:
    resource: "@CoyoteApiBundle/Controller/"
    type:     annotation
    prefix:   /

nelmio_api_doc_index:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc