coyote_api:
    resource: "@CoyoteApiBundle/Controller/"
    type:     annotation
    prefix:   /

nelmio_api_doc_index:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

ws_rest_default:
    type: rest
    resource: Coyote\ApiBundle\Controller\DefaultRestController
    prefix: /api

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin